# Generated by Django 5.2.6 on 2025-10-09 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico', null=True)),
                ('name', models.CharField(max_length=140)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('unit', models.CharField(default='kWh', max_length=32)),
                ('default_min_threshold', models.FloatField(blank=True, null=True)),
                ('default_max_threshold', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico', null=True)),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('nominal_voltage_v', models.FloatField(blank=True, null=True)),
                ('max_current_a', models.FloatField(blank=True, null=True)),
                ('standby_power_w', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico', null=True)),
                ('min_threshold', models.FloatField(blank=True, null=True)),
                ('max_threshold', models.FloatField(blank=True, null=True)),
                ('unit_override', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'product_alert_rule',
                'ordering': ['product_id', 'alert_rule_id'],
            },
        ),
        migrations.RemoveField(
            model_name='alert',
            name='device',
        ),
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
        migrations.AlterField(
            model_name='zone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.organization'),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['organization_id', 'name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='energy_kwh',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('organization', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
        migrations.AddField(
            model_name='device',
            name='max_power_w',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measured_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10),
        ),
        migrations.AddField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creación'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creación'),
        ),
        migrations.AlterField(
            model_name='device',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Nombre único dentro de la organización.', max_length=160),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AlterField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dispositivos.zone'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creación'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dispositivos.device'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creación'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Borrado lógico', null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='measurement',
            table='measurement',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='zone',
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', help_text='Estado lógico del registro.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico', null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=240)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='dispositivos.device')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='dispositivos.alertrule')),
            ],
            options={
                'verbose_name': 'Alert Event',
                'verbose_name_plural': 'Alert Events',
                'db_table': 'alert_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='triggered_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_measurements', to='dispositivos.alertrule'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['device', 'measured_at'], name='measurement_device__c1b88c_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['triggered_alert'], name='measurement_trigger_5b5387_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='dispositivos.category'),
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dispositivos.product'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'name'], name='device_organiz_34663d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['zone'], name='device_zone_id_b296ed_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['product'], name='device_product_714eb1_idx'),
        ),
        migrations.AddField(
            model_name='productalertrule',
            name='alert_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_links', to='dispositivos.alertrule'),
        ),
        migrations.AddField(
            model_name='productalertrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_alert_links', to='dispositivos.product'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='alert_rules', through='dispositivos.ProductAlertRule', to='dispositivos.product'),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['device', 'occurred_at'], name='alert_event_device__ea6084_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['alert_rule'], name='alert_event_alert_r_b494ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_afe0af_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['product'], name='product_ale_product_01a756_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['alert_rule'], name='product_ale_alert_r_acd589_idx'),
        ),
        migrations.AddIndex(
            model_name='productalertrule',
            index=models.Index(fields=['product', 'alert_rule'], name='product_ale_product_fca7e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalertrule',
            constraint=models.UniqueConstraint(fields=('product', 'alert_rule'), name='uix_product_alert_unique'),
        ),
        migrations.AddConstraint(
            model_name='productalertrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_threshold__isnull', True), ('max_threshold__isnull', True), ('min_threshold__lte', models.F('max_threshold')), _connector='OR'), name='par_min_lte_max'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['severity'], name='alert_rule_severit_cc978d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['name'], name='alert_rule_name_3749b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.CheckConstraint(condition=models.Q(('default_min_threshold__isnull', True), ('default_max_threshold__isnull', True), ('default_min_threshold__lte', models.F('default_max_threshold')), _connector='OR'), name='alert_rule_default_min_lte_max'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together={('name', 'severity')},
        ),
    ]
